[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "echo 'Building Yew Christmas Lights app...'"]

[build]
target = "index.html"
public-url = "/xmas-rs/"

[[build.assets]]
path = "images"
dest = "images"

[watch]
ignore = ["dist"]

[serve]
port = 7030
address = "127.0.0.1"
